[global]
    name = "vearch"
    data = ["datas/"]
    level = "debug"
    signkey = "vearch"
    skip_auth = true
    log = "logs"

[[masters]]
    name = "m1"
    address = "10.26.112.65"
    api_port = 8817
    etcd_port = 2378
    etcd_peer_port = 2390
    etcd_client_port = 2370
[router]
    port = 9002
    skip_auth = true
    hearbeat_interval_s = 5
[ps]
    rpc_port = 8081
    hearbeat_interval_s = 3
    raft_election_timeout_ms = 1000
    raft_snap_interval_s = 30
